trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip3 install --upgrade pip
    pip3 install -r dev-requirements.txt
  displayName: 'Install dependencies'

- script: |
    black --check pytijo_cli tests
  displayName: 'check source code formatting'

- script: |
    tox
  displayName: 'tox testing'
